language: node_js
node_js:
- '4'
- '5'
- '6'
env:
  matrix:
  - CXX=g++-4.8
  global:
  - secure: ju30KDpSYrw+nd2MmZTOjCTJu+gFNDy9auc6h/K9HhWgGX9zQ2cX0Vq4LX5EHWCImyPoVuyuxiouHoWB/eYcDtyDUoXb+EzNn/i+JXVWteQVRdbgnbDNHccGIpMYwEBrslg+iZWz5/SuxeqB/R0jd7MDK6oQBhWKAXgEYNOBEnRh814jryf93gQc8s4gONq2QoSiFk5QwDfqbvoK2o/4RsGGu3YBxy9/O8LhPTiI9YpdtjxmQtdgbchXLU0/oxv/7P/Etc5Z/0uqRwuF6YMZhJE6FT4ytLCDjaldYyMUAQ2YCT13UfouOO2gZYG0w+zpVGJ+e0hi/+6y1BCew/qNwTylMapcMpMCOsc2XLLD0HZoDrYprx8nUjZd0X859Rod+AWWEQnUhtFR7vqv69zwaH5TFR6l9uh+TragdgWUhJvWvupl1i26JBh0G1dFfWaU+rK/bmcsHK2ioPz2Ij+XrEdJV4KFtc7HPDWV1nCmiX5LA+cypDdfCNQehIufe6gArUUsV/vwtyEkTeOwzJAFgvOgufeZSivhttm/loalD1kX1JLrdR1ebxARvK2zSszeBYlFBwGCuK6sWup5Ace5TX39Ff6TRyO3YCTzaOd6k4w+Fsk93SkKLhGrDby21yIcmrkPdpDLjvR70SLb+OepemISktQpeMPrBTdfQU3J5G4=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
install: npm install
script: npm run lint
deploy:
  provider: releases
  api_key:
    secure: mCYqIo/w8NIFgEBwPilMRq9pZGULPE+oGH7x5Jp/vR8+uP3Qskvgg1lqZ4rdfeQ37m/RL4UKtQ/tRVPOwrTtZHnIg2atSItogC+y6RBfXOp4keORNOGA2ic4oxpsg+aZY6XlhXGHb1O8k0GhXu+btSBfIEISqQIOPOuLYxM/E0/tRsdi4Bw3wqj4T2j5W2aNg9G5DbDaJkq+S1hMNan8tkvscC7XTp3O7cqIEJkOe4NbOO+k9QGLIPbZ4Nf/JPeDfeJ/Slf99yxv9Lvy7MSJNqNkN8xmS93sjU4WeY5YHvDuiQZO/HBPHyBWjBmnrUReiZ3cCS5aSEPrw4t+yi71uDrLemUMnPRjecx/AM8gTxAfAZF98XyDl1SAzDWuPp2o0q+hKlJyQoXF6qqVDWTu4zkHljLhrjDVNyIewnt5ONdGw+8n64nRqL7f51Yy8O7Kw5VBgG9RmNhHLrTzMvoX+b5RLPCBxbzaO+GXGNoo9w3/Ehntbg4WeUR1DG1z1Fy7a4F9TPTv6GX8ArmOt1478ITJiwWBsmfpv1rEr5CakCanLxnctFSclDxISV+qgmX9brqz+n0X7XZV85dzL1ahBio8dZXzNzWDhe05lOWe8I4sZRbuSAKaGxPhO8fkcSSSz0tq8nO2j6vtjjypByggtkQlKC5WlmDYnRhqWr7gWFo=
  file: index.js
  on:
    tags: true
    node: '6'
